### PR TITLE
[Arch/1.20] loader tag on file name

### PR DESCRIPTION
**Pull request by TexBlock**
sorry, i forget this

### CODE REVIEW

**Comment by KrLite** [comment]
image

Maybe moving all these arch based branches to another organization is a good choice.

**Comment by KrLite** [comment]
> image
> Maybe moving all these arch based branches to another organization is a good choice.

@TexBlock If you are interested in this, @ me here. What do you want that organization to be called then?

**Comment by TexBlock** [comment]
> > image
> > Maybe moving all these arch based branches to another organization is a good choice.
> 
> @TexBlock If you are interested in this, @ me here. What do you want that organization to be called then?

Kesskou Tea Time? (fromBocchi the Rock! & K-ON!) @KrLite

**Comment by KrLite** [comment]
> > > image
> > > Maybe moving all these arch based branches to another organization is a good choice.
> > 
> > 
> > @TexBlock If you are interested in this, @ me here. What do you want that organization to be called then?
> 
> Kesskou Tea Time? (fromBocchi the Rock! & K-ON!) @KrLite

image

**Pull request merged**
