### PR TITLE
Port to forge

### PR DESCRIPTION
**Pull request by Kasualix**
Artifact is available [here](https://github.com/Kasualix/Bounced/actions/runs/5829333119)
Tested and worked perfectly.

### CODE REVIEW

**Comment by KrLite** [comment]
Thanks! But since I cannot build any Forge mods on my local machine, I may need to find out a new way to maintain the forge ports.

**Comment by Kasualix** [comment]
啊你怎么直接merge进Fabric的branch里了，不是应该先新建一个再merge进去吗
% 1P3Y4${8 ~YOUSL6}1(S3

**Comment by KrLite** [comment]
> 啊你怎么直接merge进Fabric的branch里了，不是应该先新建一个再merge进去吗 % 1P3Y4${8 ~YOUSL6}1(S3

Yes I messed it up but now it's fine

**Comment by KrLite** [comment]
One more thing: the mod should always be in the same version while providing the same functions, so actually this should be `v2.1.2` on forge.

**Comment by Kasualix** [comment]
can you upload the file on cf?

**Comment by KrLite** [comment]
My mods on Curseforge haven't been updated for a long time. I may do it later.

**Pull request merged**
